(()=>{'use strict';const D=JSON.parse(document.getElementById('loop-data').textContent),$=id=>document.getElementById(id);let mode='demo',index=Math.min(21,D.steps.length-1),playTimer=null,liveTimer=null,busy=false,requestVersion=0,current=null;
const node=(tag,text)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;},money=v=>v==null?'—':'$'+v.toFixed(2),pct=v=>v==null?'—':(v*100).toFixed(1)+'%',odds=v=>v==null?'—':v.toFixed(2),signed=v=>v==null?'—':(v>=0?'+':'')+v.toFixed(1);
function position(){if(!$('position-enabled').checked)return null;const side=$('position-side').value,n=Number($('position-shares').value),cost=Number($('position-cost').value);if(!['home','away'].includes(side)||!Number.isFinite(n)||!Number.isFinite(cost)||n<=0||cost<0||cost>n)throw Error('Check your shares and original cost.');return{side,shares:n,cost};}
function hedgeOptions(s,q,pos,budget){const own=q[pos.side],other=q[pos.side==='home'?'away':'home'],options=[{kind:'hold',side:pos.side,shares:0,added_cost:0,if_held_wins:pos.shares-pos.cost,if_other_wins:-pos.cost,floor:-pos.cost}];if(s.quote_state==='final'||!own||!other||own.condition_id!==other.condition_id||own.token_id===other.token_id)return options;const usable=side=>!window.newsLoopAnalysis.quoteProblems(q[side],s,side).length;const opposite=pos.side==='home'?'away':'home';if(usable(opposite)){const f=window.newsLoopAnalysis.walk(other,budget,.002,pos.shares);if(f.shares&&f.cost>=(other.minimum_notional||0)&&f.shares>=(other.minimum_shares||0)){const a=pos.shares-pos.cost-f.cost,b=f.shares-pos.cost-f.cost;options.push({kind:'hedge',side:opposite,shares:f.shares,added_cost:f.cost,if_held_wins:a,if_other_wins:b,floor:Math.min(a,b),balanced:Math.abs(f.shares-pos.shares)<1e-6});}}if(usable(pos.side)){let remaining=pos.shares,proceeds=0,filled=0;const levels=(own.bids||[]).map(r=>({price:Number(r.price),size:Number(r.size)}));if(!levels.some(r=>!Number.isFinite(r.price)||r.price<=0||r.price>=1||!Number.isFinite(r.size)||r.size<0)){levels.sort((a,b)=>b.price-a.price);for(const r of levels){const n=Math.min(remaining,r.size),fee=own.fee_rate*Math.pow(r.price*(1-r.price),own.fee_exponent||1);proceeds+=n*(r.price-fee-.002);filled+=n;remaining-=n;if(remaining<=1e-8)break;}if(filled&&filled>=(own.minimum_shares||0)&&proceeds>=(own.minimum_notional||0)){const a=remaining+proceeds-pos.cost,b=proceeds-pos.cost;options.push({kind:'reduce',side:pos.side,shares:filled,added_cost:0,proceeds,if_held_wins:a,if_other_wins:b,floor:Math.min(a,b)});}}}return options;}
window.matchMath={hedgeOptions};
function demoView(){const item=D.steps[index],s=item.snapshot,budget=Number($('budget').value),q=s.market_quotes||{},names={home:D.home_team,away:D.away_team};if(!Number.isFinite(budget)||budget<1||budget>100000)throw Error('Choose a budget between $1 and $100,000.');const r=window.newsLoopAnalysis.compare(s,q,budget,2,.002),view=JSON.parse(JSON.stringify(item.view));view.teams=r.routes.map(row=>{const fill=row.fill||{},quote=q[row.side]||{};return{side:row.side,team:names[row.side],probability:row.p,model_odds:row.p?1/row.p:null,market_odds:fill.shares?1/fill.effective_price:null,edge_pp:row.edge,quote_available:!row.problems.length};});const pos=position();let action={title:'Wait for a better entry',kind:'wait',reason:'No clear advantage after costs. Keep your budget available.',amount:0,options:[]};if(s.quote_state==='final'){action={title:'Game finished',kind:'finished',reason:'The final score is confirmed. No new game-winner action.',amount:0,options:[]};}else if(pos){const options=hedgeOptions(s,q,pos,budget),best=[...options].sort((a,b)=>b.floor-a.floor||a.added_cost-b.added_cost)[0];action={...best,amount:best.added_cost,options,title:best.kind==='hedge'?'Hedge with '+names[best.side]:best.kind==='reduce'?'Reduce '+names[best.side]:'Hold your position',reason:best.kind==='hedge'?'Buy '+best.shares.toFixed(1)+' opposite shares. Lower game-result P/L improves to '+money(best.floor)+'.':best.kind==='reduce'?'Selling '+best.shares.toFixed(1)+' shares improves the lower game-result P/L to '+money(best.floor)+'.':'No available hedge improves the lower of the two game-result payouts.'};}else if(r.candidate!=='wait'){const best=r.routes.find(row=>row.side===r.candidate);action={title:'Buy '+names[r.candidate],kind:'buy',reason:'The estimated win chance is '+best.edge.toFixed(1)+' percentage points above the all-in entry cost.',amount:best.fill.cost,ev:best.ev,shares:best.fill.shares,options:[]};}view.action=action;return view;}
function svg(tag,attrs){const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs||{}))el.setAttribute(k,String(v));return el;}function textSVG(root,value,x,y,attrs={}){const el=svg('text',{x,y,'font-size':11,fill:'#657981',...attrs});el.textContent=value;root.appendChild(el);}
function draw(view){const host=$('probchart');host.replaceChildren();const rows=view.curve||[],W=Math.max(310,host.clientWidth),H=245,L=39,R=10,T=30,B=28,end=Math.max(48,...rows.map(r=>r.minute)),x=t=>L+t/end*(W-L-R),y=p=>H-B-p*(H-T-B);const root=svg('svg',{viewBox:`0 0 ${W} ${H}`,role:'img','aria-label':'Model and market win chance through four quarters'});for(let q=0;q<4;q++){root.appendChild(svg('rect',{x:x(q*12),y:T,width:x((q+1)*12)-x(q*12),height:H-T-B,fill:q%2?'#f0f5f6':'#f8fafb'}));textSVG(root,'Q'+(q+1),x(q*12+6),18,{'text-anchor':'middle'});}for(const p of [0,.5,1]){root.appendChild(svg('line',{x1:L,x2:W-R,y1:y(p),y2:y(p),stroke:'#dbe5e7'}));textSVG(root,Math.round(p*100)+'%',L-6,y(p)+4,{'text-anchor':'end'});}for(const min of [0,12,24,36,48])textSVG(root,String(min),x(min),H-6,{'text-anchor':'middle'});for(const [key,color,dash]of [['probability','#067565',''],['market','#8056b1','4 4']]){const valid=rows.filter(r=>r[key]!=null);root.appendChild(svg('path',{d:valid.map((r,i)=>(i?'L':'M')+x(r.minute)+','+y(r[key])).join(' '),fill:'none',stroke:color,'stroke-width':2.2,'stroke-dasharray':dash}));if(valid.length){const last=valid[valid.length-1];root.appendChild(svg('circle',{cx:x(last.minute),cy:y(last[key]),r:3.5,fill:color}));}}
for(const event of view.events||[]){const at=rows.find(r=>r.clock===event.clock);if(!at)continue;const marker=svg('circle',{cx:x(at.minute),cy:y(at.probability),r:4,fill:'#fff',stroke:'#067565','stroke-width':1.5}),title=svg('title');title.textContent=event.clock+' · '+event.headline+' · '+signed(event.impact_pp)+' percentage points';marker.appendChild(title);root.appendChild(marker);}host.appendChild(root);}
function render(view){current=view;$('awayname').textContent=$('awaylogo').textContent=view.away_team;$('homename').textContent=$('homelogo').textContent=view.home_team;const s=view.score;$('score').textContent=s?s.away_score+' – '+s.home_score:'— – —';$('clock').textContent=view.quote_state==='final'?'Final':['stale_score','score_unavailable','invalid_final_tie'].includes(view.quote_state)?'Last known · '+view.clock:view.clock;$('modebadge').textContent=mode==='demo'?'SIMULATION':'LIVE';$('updatestatus').textContent=mode==='demo'?'Simulated match & Polymarket prices':'Auto-refresh · every 5 seconds';$('matchdate').textContent=mode==='demo'?'Replay, not a live NBA game':'Updated '+new Date(view.as_of).toLocaleTimeString();$('quarters').replaceChildren();if(mode==='demo')for(let q=1;q<=4;q++){const end=D.steps.slice(0,index+1).map(r=>r.snapshot.score).filter(s=>s&&s.period===q&&s.clock_seconds===0).pop();$('quarters').appendChild(node('span','Q'+q+(end?'  '+end.away_score+'–'+end.home_score:'')));}
$('oddsrows').replaceChildren();for(const row of view.teams){const tr=node('tr');for(const value of [row.team,pct(row.probability),odds(row.model_odds),odds(row.market_odds),row.edge_pp==null?'—':signed(row.edge_pp)+' pp'])tr.appendChild(node('td',value));if(row.price_status==='Last seen')tr.children[3].appendChild(node('small','Last seen'));tr.children[4].className=row.edge_pp>=0?'positive':'negative';$('oddsrows').appendChild(tr);}
const a=view.action;$('actionlabel').textContent=mode==='demo'?'Simulated next step':a.options&&a.options.length?'Position protection':'Suggested next step';$('actiontitle').textContent=a.title;$('actionreason').textContent=a.reason;$('amountlabel').textContent=a.kind==='reduce'?'Estimated sale proceeds':'Suggested spend';$('actionamount').textContent=money(a.kind==='reduce'?a.proceeds:a.amount);$('resultlabel').textContent=a.floor!=null?'Lower game-result P/L':'Estimated net return';$('actionresult').textContent=a.floor!=null?money(a.floor):a.ev!=null?money(a.ev):'—';$('why').textContent=a.options&&a.options.length?'Compare the lower payout across two completed-game results, after costs. Canceled-game payouts follow market rules. A buying edge alone is not a hedge.':'We compare buying either team with waiting, after estimated fees, depth and a 2 percentage-point model stress buffer. Estimates are being validated.';$('hedgeoutcomes').replaceChildren();if(a.options&&a.options.length){const table=node('table');table.className='outcomes';const head=node('tr');['Option','Held team wins','Other team wins'].forEach(v=>head.appendChild(node('th',v)));table.appendChild(head);for(const o of a.options){const tr=node('tr');[o.kind==='hedge'?'Buy opposite':o.kind==='reduce'?'Reduce':'Hold',money(o.if_held_wins),money(o.if_other_wins)].forEach(v=>tr.appendChild(node('td',v)));table.appendChild(tr);}$('hedgeoutcomes').appendChild(table);}
$('events').replaceChildren();if(!view.events.length)$('events').appendChild(node('p','No new player alerts at this point. Score and market monitoring continue.'));for(const event of [...view.events].reverse().slice(0,4)){const el=node('div');el.className='feed-item';const stamp=node('div',event.clock+(event.synthetic?' · Simulated update':''));stamp.className='feed-time';el.appendChild(stamp);if(!event.synthetic&&event.source){const source=node(event.url&&event.url.startsWith('https://')?'a':'span',event.source.replace(/^x:/,'@').replace(/_/g,' '));source.className='subtle';if(source.tagName==='A'||source.tag==='a'){source.href=event.url;source.target='_blank';source.rel='noopener noreferrer';}el.appendChild(source);}el.appendChild(node('p',event.headline));const impact=node('div',!event.selected?'Unconfirmed update · no additional change':view.home_team+' win chance '+signed(event.impact_pp)+' pp');impact.className='feed-impact '+(event.impact_pp>=0?'positive':'negative');el.appendChild(impact);$('events').appendChild(el);}
$('connection').textContent=mode==='demo'?'Prices update with every replay step.':view.connection_note||(view.market_connected?'Polymarket connected · '+(view.market_updated_at?'checked '+new Date(view.market_updated_at).toLocaleTimeString():'monitoring'):'Looking for a matching Polymarket market…');$('marketlink').href=view.market_url||'https://polymarket.com/sports/nba';$('footnote').textContent=mode==='demo'?'Demo uses simulated scores, news and prices. Model estimates are still being validated.':'Live game updates and public market prices. Prices can change; model estimates are being validated.';if(mode==='live'&&view.news_health==='degraded')$('footnote').textContent+=' Player-news coverage is incomplete.';if(mode==='live'&&view.freshness==='source_timestamp_unverified')$('footnote').textContent+=' Score source time is unverified.';$('replaycontrols').hidden=mode!=='demo';$('seek').max=D.steps.length-1;$('seek').value=index;$('progress').textContent=(index+1)+' / '+D.steps.length;$('next').disabled=index===D.steps.length-1;$('play').textContent=playTimer?'Pause':'Play';draw(view);}
function stop(){if(playTimer)clearInterval(playTimer);playTimer=null;}function showDemo(){try{render(demoView());}catch(e){$('actiontitle').textContent='Check your inputs';$('actionreason').textContent=e.message;$('actionamount').textContent='$0.00';$('actionresult').textContent='—';}}
const base=location.protocol==='file:'?'http://127.0.0.1:8766':'';async function api(path){const response=await fetch(base+path,{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Live data is unavailable.');return data;}
function clearLive(message) {
  current=null;
  $('modebadge').textContent='CONNECTING'; $('updatestatus').textContent='Auto-refresh · every 5 seconds';
  $('score').textContent='— – —'; $('clock').textContent='Waiting for current data'; $('matchdate').textContent='';
  $('homename').textContent=$('homelogo').textContent='Home'; $('awayname').textContent=$('awaylogo').textContent='Away';
  for(const id of ['oddsrows','events','quarters','probchart','hedgeoutcomes']) $(id).replaceChildren();
  $('actionlabel').textContent='Suggested next step'; $('actiontitle').textContent='Waiting for live data';
  $('actionreason').textContent='Game and market data must be current before comparing an action.';
  $('actionamount').textContent='$0.00'; $('actionresult').textContent='—'; $('connection').textContent=message;
  $('why').textContent='Monitoring the live connection. No current action is available.';
  $('footnote').textContent='Live data connection pending. The demo remains available.';
  $('marketlink').href='https://polymarket.com/sports/nba';
}
let catalogAt=0;
async function refreshLive() {
  if(mode!=='live'||busy)return;
  busy=true; const version=requestVersion;
  try {
    if(!$('games').value || Date.now()-catalogAt>=30000) {
      const data=await api('/api/games');
      if(mode!=='live'||version!==requestVersion)return;
      const previous=$('games').value;
      $('games').replaceChildren();
      for(const game of data.games) {const option=node('option',game.label);option.value=game.game_id;$('games').appendChild(option);}
      $('games').value=data.games.some(g=>g.game_id===previous)?previous:data.games.length?data.games[0].game_id:'';
      catalogAt=Date.now();
      if(!$('games').value){clearLive('No NBA games are listed right now. Monitoring the schedule automatically.');return;}
      if(previous && previous!==$('games').value) $('position-enabled').checked=false;
    }
    const pos=position(), params=new URLSearchParams({game_id:$('games').value,budget:$('budget').value});
    if(pos){params.set('position_side',pos.side);params.set('position_shares',pos.shares);params.set('position_cost',pos.cost);}
    const view=await api('/api/match?'+params);
    if(mode==='live'&&version===requestVersion)render(view);
  } catch(e) {
    if(mode==='live'&&version===requestVersion)clearLive(e.message+' Retrying automatically.');
  } finally {busy=false;}
}
async function chooseLive() {
  stop(); mode='live'; requestVersion++; catalogAt=0; $('position-enabled').checked=false;
  $('demo').setAttribute('aria-selected',false);$('live').setAttribute('aria-selected',true);
  $('games').hidden=false;$('replaycontrols').hidden=true;
  clearLive('Finding today’s NBA games and matching Polymarket prices…');
  if(!liveTimer)liveTimer=setInterval(refreshLive,5000);
  await refreshLive();
}
$('demo').onclick=()=>{requestVersion++;mode='demo';$('position-enabled').checked=false;if(liveTimer)clearInterval(liveTimer);liveTimer=null;$('games').hidden=true;$('demo').setAttribute('aria-selected',true);$('live').setAttribute('aria-selected',false);showDemo();};$('live').onclick=chooseLive;$('games').onchange=()=>{requestVersion++;$('position-enabled').checked=false;clearLive('Connecting to the selected match…');refreshLive();};$('seek').oninput=e=>{stop();index=+e.target.value;showDemo();};$('next').onclick=()=>{stop();index=Math.min(D.steps.length-1,index+1);showDemo();};$('restart').onclick=()=>{stop();index=0;showDemo();};$('play').onclick=()=>{if(playTimer){stop();showDemo();return;}if(index===D.steps.length-1)index=0;playTimer=setInterval(()=>{index=Math.min(index+1,D.steps.length-1);if(index===D.steps.length-1)stop();showDemo();},1100);showDemo();};for(const id of ['budget','position-enabled','position-side','position-shares','position-cost'])$(id).onchange=()=>{if(mode==='demo')showDemo();else{requestVersion++;clearLive('Updating your comparison…');refreshLive();}};window.addEventListener('resize',()=>{if(current)draw(current);});showDemo();})();
