"""Prototype synthetic season in the frozen-table format, for developing models before D1 lands.

The numbers are generated by make_sample_data.py, not real NBA results; never
report them as findings.
"""
import pandas as pd

from data_sources.nba_stats import build_games, build_player_games
from tables import SEASON_DIR


def synthetic_tables():
    players = pd.read_parquet(SEASON_DIR / "player_regular.parquet")
    teams = pd.read_parquet(SEASON_DIR / "team_regular.parquet")
    matchup = players.drop_duplicates(["GAME_ID", "TEAM_ID"])[["GAME_ID", "TEAM_ID", "MATCHUP"]]
    teams = teams.merge(matchup, on=["GAME_ID", "TEAM_ID"])
    days = pd.to_datetime(teams.GAME_DATE).dt.strftime("%Y-%m-%d")
    tips = pd.DataFrame({"game_id": teams.GAME_ID.astype(str),
                         "tip_time": pd.to_datetime(days + " 19:30").dt.tz_localize("America/New_York")
                         .dt.tz_convert("UTC")}).drop_duplicates("game_id")
    games = build_games(teams, tips)
    return build_player_games(players), games
