"""add agent trading and learning tables

Revision ID: 5f1f68be9221
Revises: 944233f52b96
Create Date: 2026-10-04 09:05:02.216627+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5f1f68be9221'
down_revision: Union[str, Sequence[str], None] = '944233f52b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_game_id'), 'agent_runs', ['game_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('forecasts',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('forecast_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_forecast_type'), 'forecasts', ['forecast_type'], unique=False)
    op.create_index(op.f('ix_forecasts_game_id'), 'forecasts', ['game_id'], unique=False)
    op.create_index(op.f('ix_forecasts_player_id'), 'forecasts', ['player_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=False),
    sa.Column('contract_id', sa.String(length=200), nullable=False),
    sa.Column('selection', sa.String(length=200), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('market_probability', sa.Float(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=True),
    sa.Column('ask_price', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_contract_id'), 'market_snapshots', ['contract_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_game_id'), 'market_snapshots', ['game_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_market_type'), 'market_snapshots', ['market_type'], unique=False)
    op.create_index(op.f('ix_market_snapshots_observed_at'), 'market_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_provider'), 'market_snapshots', ['provider'], unique=False)
    op.create_table('trade_proposals',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('market_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=False),
    sa.Column('probability_gap', sa.Float(), nullable=False),
    sa.Column('proposed_size', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_proposals_agent_run_id'), 'trade_proposals', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_forecast_id'), 'trade_proposals', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_game_id'), 'trade_proposals', ['game_id'], unique=False)
    op.create_index(op.f('ix_trade_proposals_market_snapshot_id'), 'trade_proposals', ['market_snapshot_id'], unique=False)
    op.create_table('risk_checks',
    sa.Column('trade_proposal_id', sa.UUID(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trade_proposal_id'], ['trade_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_checks_trade_proposal_id'), 'risk_checks', ['trade_proposal_id'], unique=False)
    op.create_table('trades',
    sa.Column('trade_proposal_id', sa.UUID(), nullable=False),
    sa.Column('risk_check_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('closing_price', sa.Float(), nullable=True),
    sa.Column('closing_line_value', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['risk_check_id'], ['risk_checks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_proposal_id'], ['trade_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_mode'), 'trades', ['mode'], unique=False)
    op.create_index(op.f('ix_trades_risk_check_id'), 'trades', ['risk_check_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_trade_proposal_id'), 'trades', ['trade_proposal_id'], unique=False)
    op.create_table('reviews',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('cause', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_agent_run_id'), 'reviews', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_reviews_cause'), 'reviews', ['cause'], unique=False)
    op.create_index(op.f('ix_reviews_trade_id'), 'reviews', ['trade_id'], unique=False)
    op.create_table('rules',
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_review_id'), 'rules', ['review_id'], unique=False)
    op.create_index(op.f('ix_rules_status'), 'rules', ['status'], unique=False)
    op.create_table('rule_backtests',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('cases_tested', sa.Integer(), nullable=False),
    sa.Column('cases_improved', sa.Integer(), nullable=False),
    sa.Column('calibration_before', sa.Float(), nullable=True),
    sa.Column('calibration_after', sa.Float(), nullable=True),
    sa.Column('clv_before', sa.Float(), nullable=True),
    sa.Column('clv_after', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_backtests_rule_id'), 'rule_backtests', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_backtests_rule_id'), table_name='rule_backtests')
    op.drop_table('rule_backtests')
    op.drop_index(op.f('ix_rules_status'), table_name='rules')
    op.drop_index(op.f('ix_rules_review_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_reviews_trade_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_cause'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_agent_run_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_trades_trade_proposal_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_risk_check_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_mode'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_risk_checks_trade_proposal_id'), table_name='risk_checks')
    op.drop_table('risk_checks')
    op.drop_index(op.f('ix_trade_proposals_market_snapshot_id'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_game_id'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_forecast_id'), table_name='trade_proposals')
    op.drop_index(op.f('ix_trade_proposals_agent_run_id'), table_name='trade_proposals')
    op.drop_table('trade_proposals')
    op.drop_index(op.f('ix_market_snapshots_provider'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_observed_at'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_market_type'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_game_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_contract_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_forecasts_player_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_game_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_type'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_game_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###