"""create core nba tables

Revision ID: 944233f52b96
Revises: 
Create Date: 2026-10-04 08:58:54.554422+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '944233f52b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('nba_team_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_abbreviation'), 'teams', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_teams_nba_team_id'), 'teams', ['nba_team_id'], unique=True)
    op.create_table('games',
    sa.Column('nba_game_id', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('season_type', sa.String(length=50), nullable=True),
    sa.Column('home_team_id', sa.UUID(), nullable=False),
    sa.Column('away_team_id', sa.UUID(), nullable=False),
    sa.Column('tipoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_away_team_id'), 'games', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_nba_game_id'), 'games', ['nba_game_id'], unique=True)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    op.create_index(op.f('ix_games_tipoff_time'), 'games', ['tipoff_time'], unique=False)
    op.create_table('players',
    sa.Column('nba_player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('current_team_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_current_team_id'), 'players', ['current_team_id'], unique=False)
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_nba_player_id'), 'players', ['nba_player_id'], unique=True)
    op.create_table('news_events',
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('player_status', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_events_event_type'), 'news_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_news_events_game_id'), 'news_events', ['game_id'], unique=False)
    op.create_index(op.f('ix_news_events_ingested_at'), 'news_events', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_news_events_player_id'), 'news_events', ['player_id'], unique=False)
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_events_team_id'), 'news_events', ['team_id'], unique=False)
    op.create_table('player_game_stats',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('field_goals_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=True),
    sa.Column('three_points_made', sa.Integer(), nullable=True),
    sa.Column('three_points_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('usage_pct', sa.Float(), nullable=True),
    sa.Column('true_shooting_pct', sa.Float(), nullable=True),
    sa.Column('offensive_rating', sa.Float(), nullable=True),
    sa.Column('defensive_rating', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('plus_minus', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game_stats_game_player')
    )
    op.create_index(op.f('ix_player_game_stats_game_id'), 'player_game_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_player_id'), 'player_game_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_game_stats_team_id'), 'player_game_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_game_stats_team_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_player_id'), table_name='player_game_stats')
    op.drop_index(op.f('ix_player_game_stats_game_id'), table_name='player_game_stats')
    op.drop_table('player_game_stats')
    op.drop_index(op.f('ix_news_events_team_id'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_player_id'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_ingested_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_game_id'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_event_type'), table_name='news_events')
    op.drop_table('news_events')
    op.drop_index(op.f('ix_players_nba_player_id'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_index(op.f('ix_players_current_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_tipoff_time'), table_name='games')
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_nba_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_away_team_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_nba_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_abbreviation'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###